# Arrays

In Python, arrays are containers which are able to store more than one item at the same time, from the same data type. Specifically, they are an ordered collection of elements with every value being of the same data type. Elements in an array can be accessed directly using an index or a subscript. This means you can quickly retrieve the value at a specific position in constant time.

**What's the Difference between Python Lists and Python Arrays?**

Lists and arrays behave similarly. Just like arrays, lists are an ordered sequence of elements. They are also mutable and not fixed in size, which means they can grow and shrink throughout the life of the program. Items can be added and removed, making them very flexible to work with.

However, lists and arrays are not the same thing.

Lists store items that are of various data types. This means that a list can contain integers, floating point numbers, strings, or any other Python data type, at the same time. That is not the case with arrays.

**In Python, lists and arrays (NumPy arrays, in particular) serve different purposes, and the choice between them depends on the specific requirements of your task. Here are some considerations that might lead you to choose arrays over lists in certain scenarios:**

<br>

**1 - Numerical Operations and Efficiency:**

If your primary use case involves numerical operations or large-scale mathematical computations, NumPy arrays are often a better choice. NumPy is a powerful numerical computing library in Python, and its arrays are implemented in C, which makes them more efficient for numerical operations than Python lists.

<br>

**2 - Memory Efficiency:**

NumPy arrays are more memory-efficient than lists, especially for large datasets. NumPy uses a more compact internal representation for arrays compared to Python lists.

<br>

**3 - Multidimensional Arrays:**

NumPy provides support for multidimensional arrays. This is particularly useful for tasks like linear algebra, image processing, and working with multi-dimensional datasets.

<br>

**Zip function:** 

It is a built-in function in Python that combines multiple iterables (lists, tuples, etc.) element-wise. It returns an iterator of tuples where the i-th tuple contains the i-th element from each of the input iterables. If the input iterables are of unequal length, zip stops creating tuples when the shortest input iterable is exhausted.

Here's a simple example:

In [3]:
list1 = [1, 2, 3]
list2 = ['a', 'b', 'c']

# Using zip to combine the two lists
zipped_result = zip(list1, list2)

print(next(zipped_result))
print(next(zipped_result))
print(next(zipped_result))

print(zipped_result)

zipped_result2 = zip(list1, list2)

# Converting the result to a list for display
result_list = list(zipped_result2)

print(result_list)

(1, 'a')
(2, 'b')
(3, 'c')
[(1, 'a'), (2, 'b'), (3, 'c')]


**Example illustrating the efficiency of NumPy arrays for numerical operations:**

In [4]:
import numpy as np

# Using Python lists
python_list1 = [1, 2, 3]
python_list2 = [4, 5, 6]
result_list = [a + b for a, b in zip(python_list1, python_list2)]

print(result_list)

#Other solution:

result_list2 = []

for i in range(len(python_list1)):
    result_list2.append(python_list1[i] + python_list2[i])

print(result_list2)


# Using NumPy arrays
numpy_array1 = np.array([1, 2, 3])
numpy_array2 = np.array([4, 5, 6])
result_array = numpy_array1 + numpy_array2
print(result_array)

[5, 7, 9]
[5, 7, 9]
[5 7 9]


In this example, both approaches achieve the same result, but the NumPy version is more concise and efficient, especially for larger datasets.

It's important to note that for general-purpose programming and when you don't require the advanced features provided by NumPy, Python lists are often sufficient and more convenient. The choice between lists and arrays depends on the nature of the tasks you need to accomplish.

**1. Creating Arrays from Lists:**

In [11]:
import numpy as np

# 1D array
arr1 = np.array([1, 2, 3, 4, 5])

# Printing out the whole array
print(arr1)

# Printing out the 3rd item in the array (since the count starts from 0)
print(arr1[2]) #Output: 3

# Number of dimensions
print(arr1.ndim) #Output: 1

# Number of columns and lines
print(arr1.shape) #Output: (5,) which means that it has 5 columns and 1 line

# Size of the array
print(arr1.size) #Output: 5

# Byte size of the array
print(arr1.itemsize) #Output: 8

# Data type ot the elements
print(arr1.dtype) #Output: int64, which means that it is 64 bit signed integer


# 2D array (matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Printing out the whole array
print(arr2)

# Printing out the 1st item from the 3rd dimension (since the count starts from 0 in each dimension)
print(arr2[2,0]) # Dimension then element, Output: 7

# Number of dimensions
print(arr2.ndim) #Output: 2

# Number of columns and lines
print(arr2.shape) #Output: (3,3) which means that it has 3 columns and 3 lines

# Size of the array
print(arr2.size) #Output: 9

# Byte size of the array
print(arr2.itemsize) #Output: 8

# Data type ot the elements
print(arr1.dtype) #Output: int64, which means that it is 64 bit signed integer


[1 2 3 4 5]
3
1
(5,)
5
8
int64
[[1 2 3]
 [4 5 6]
 [7 8 9]]
7
2
(3, 3)
9
8
int64


Capacity

Int16 - (-32,768 to +32,767) It can operate with 16 bit (15 characted long binary code)

Int32 - (-2,147,483,648 to +2,147,483,647) It can operate with 32 bit (31 characted long binary code)

Int64 - (-9,223,372,036,854,775,808 to +9,223,372,036,854,775,807) It can operate with 64 bit (63 characted long binary code)

**2. Creating Arrays with Initial Values:**

In [24]:
# Array of zeros
zeros_array = np.zeros((2, 3))  # 2x3 array of zeros

print(zeros_array)

# Array of ones
ones_array = np.ones((3, 4))  # 3x4 array of ones
print(ones_array)

# Array with a constant value
constant_array = np.full((2, 2), 7)  # 2x2 array with all elements set to 7
print(constant_array)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[7 7]
 [7 7]]


**3. Creating Arrays with Ranges:**

In [26]:
# Range of values
range_array = np.arange(0, 10, 2)  # Start, stop, step
print(range_array)

# Evenly spaced values
linspace_array = np.linspace(0, 1, 5)  # Start, stop, number of points
print(linspace_array)

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


**4. Creating Random Arrays:**

In [38]:
# Random values between 0 and 1
random_array = np.random.rand(3, 3)  # 3x3 array
print(random_array)

# np.random is not a function itself, but rather a list of functions
x = np.random.random(3) # Returns 3 random numbers between 0 and 1
print(x)

# Random integers within a range
random_int_array = np.random.randint(1, 10, (2, 2))  # 2x2 array of random integers (1 to 10)
print(random_int_array)

[[0.34789411 0.19480659 0.32534595]
 [0.14576934 0.29967501 0.05312243]
 [0.24438086 0.61053006 0.66374851]]
[0.61246628 0.95473134 0.7206305 ]
[[3 6]
 [9 8]]


**Indexing and slicing**

In [10]:
# 1D array
arr1 = np.array([1, 2, 3, 4, 5])

print(arr1) #Output: [1 2 3 4 5]

# Accessing elements
element = arr1[2]  # Access the element at index 2

print(element) #Output: 3


# 2D array (matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr2)

# Accessing elements
element2 = arr2[2,1] # Access the element at line 3, column 2

print(element2) #Output: 8



# Slicing 1D array
slice_result = arr1[1:4]  # Slice from index 1 to 3 (exclusive)

print(slice_result) #Output: [2 3 4]

slice_result2 = arr1[2:] # Slice from index 2 (contains 2nd index)

print(slice_result2) #Output: [3 4 5]

slice_result3 = arr1[:2] # Slice until index 2 (doesn't contain 2nd index)

print(slice_result3) #Output: [1 2]



# Slicing 2D array

slice_rows = arr2[0:1, 1] # Slicing the first row, and second column. With this method we don't get extra []

print(slice_rows) #Output: [2]

slice_rows2 = arr2[1:3, 1] # Slicing the second and thrird row, and second column. With this method we don't get extra []

print(slice_rows2) #Output: [5 8]

slice_rows3 = arr2[1:2, 0:3] # Slicing the second row, and columns 1 to 3

print(slice_rows3) #Output: [[4 5 6]]

slice_rows4 = arr2[1:2,:] # Slicing the second row, and all the columns

print(slice_rows4) #Output: [[4 5 6]]

slice_rows4 = arr2[2,:] # Slicing 3rd row, and all the columns. With this method we don't get extra []

print(slice_rows4) #Output: [7 8 9]



slice_cols = arr2[1, 0:1]  # Slicing the second row and first column. With this method we don't get extra []

print(slice_cols) #Output: [4]

slice_cols2 = arr2[1, 1:3]  # Slicing the second row and 2nd + 3rd column. With this method we don't get extra []

print(slice_cols2) #Output: [5 6]

slice_cols3 = arr2[0:3, 1:2]  # Slicing rows 1 to 3 and 2nd column

print(slice_cols3) #Output: [ [2] [5] [8] ] transposed

slice_cols4 = arr2[:, 1:2]  # Slicing all the rows and 2nd column

print(slice_cols4) #Output: [ [2] [5] [8] ] transposed

slice_cols5 = arr2[:, 2]  # Slicing all the rows and 3rd column

print(slice_cols5) #Output: [3 6 9]


# Slicing with steps

slice_step = arr2[:, 0:3:2]  # All rows and columns 1 to 3 with a step of 2
print(slice_step) #Output: [[1 3] [4 6] [7 9]] transposed



# Boolean indexing for 1D array
bool_index = arr1 > 3

print(bool_index) #Output: [F F F T T]

# We create an array, which shows only True values
filtered_array = arr1[bool_index]

print(filtered_array) #Output: [4 5]

# Boolean indexing for 2D array
bool_index2 = arr2 > 3

print(bool_index2) #Output: [F F F T T T T T T]

# We create an array, which shows only those elements, which have True values assigned
filtered_array2 = arr2[bool_index2] 

print(filtered_array2) #Output: [4 5 6 7 8 9]

[1 2 3 4 5]
3
[[1 2 3]
 [4 5 6]
 [7 8 9]]
8
[2 3 4]
[4 5]
[1 2]
[2]
[5 8]
[[4 5 6]]
[[4 5 6]]
[7 8 9]
[4]
[5 6]
[[2]
 [5]
 [8]]
[[2]
 [5]
 [8]]
[3 6 9]
[[1 3]
 [4 6]
 [7 9]]
[False False False  True  True]
[4 5]
[[False False False]
 [ True  True  True]
 [ True  True  True]]
[4 5 6 7 8 9]


**Appending elements**

In [12]:
# 1D array
arr1 = np.array([1, 2, 3, 4, 5])

print(arr1) # Output: [1 2 3 4 5]

# Append elements to a 1D array
arr1 = np.append(arr1, 6)

print(arr1) # Output: [1 2 3 4 5 6]

x = np.array([1,2])

# Append multiple elements at once
arr1 = np.append(arr1, x)

print(arr1) # Output: [1 2 3 4 5 6 1 2]


# 2D array (matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr2)
print(arr2.ndim) #Output: 2

# Append a row to a 2D array
new_row = np.array([10, 11, 12])
print(new_row.ndim) #Output: 1

# The new_row variable is still a 1D variable, we have to reshape it to 2D
new_row_2d = new_row.reshape(1, -1)

print(new_row_2d.ndim) #Output: 2

print(new_row_2d) #Output: [[10, 11, 12]]

# Appending to the bottom
arr2 = np.append(arr2, new_row_2d, axis=0)

print(arr2)


# Append a column to a 2D array
new_column = np.array([1,2,3,4])

print(new_column)

# The new_column variable is still a 1D variable, we have to reshape it to 2D
new_column2 = new_column.reshape(-1,1)

print(new_column2)

# Appending to the right
arr2 = np.append(arr2, new_column2, axis=1)

print(arr2)

[1 2 3 4 5]
[1 2 3 4 5 6]
[1 2 3 4 5 6 1 2]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
1
2
[[10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]
[[ 1  2  3  1]
 [ 4  5  6  2]
 [ 7  8  9  3]
 [10 11 12  4]]


1. Basic Reshaping of 1D Arrays:

In [206]:
# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5, 6])

# Reshape to a 2D array with 2 rows and 3 columns
arr_2d = np.reshape(arr_1d, (2, 3))

print("Original 1D array:")
print(arr_1d)

print("\nReshaped 2D array:")
print(arr_2d)

Original 1D array:
[1 2 3 4 5 6]

Reshaped 2D array:
[[1 2 3]
 [4 5 6]]


2. Reshaping with -1 (Automatic Inference):

In [207]:
# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5, 6])

# Reshape to a 2D array with an inferred number of rows. Python will know by itself how many rows should it use to get 3 columns
arr_2d = np.reshape(arr_1d, (-1, 3))

print("Original 1D array:")
print(arr_1d)

print("\nReshaped 2D array with automatic inference:")
print(arr_2d)

Original 1D array:
[1 2 3 4 5 6]

Reshaped 2D array with automatic inference:
[[1 2 3]
 [4 5 6]]


3. Reshaping into a Column Vector:

In [208]:
# Create a 1D array
arr_1d = np.array([1, 2, 3, 4])

# Reshape to a column vector
column_vector = np.reshape(arr_1d, (-1, 1))

print("Original 1D array:")
print(arr_1d)

print("\nReshaped column vector:")
print(column_vector)

Original 1D array:
[1 2 3 4]

Reshaped column vector:
[[1]
 [2]
 [3]
 [4]]


4. Reshaping with Multiple Dimensions:

In [210]:
# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5, 6])

# Reshape to a 3D array with 2 levels, 1 row, and 3 columns
arr_3d = np.reshape(arr_1d, (2, 1, 3))

print("Original 1D array:")
print(arr_1d)

print("\nReshaped 3D array:")
print(arr_3d)

Original 1D array:
[1 2 3 4 5 6]

Reshaped 3D array:
[[[1 2 3]]

 [[4 5 6]]]


**Inserting elements**

In [213]:
# 1D array
arr1 = np.array([1, 2, 3, 4, 5])

print(arr1)

# Insert element at index 2 in a 1D array
arr1 = np.insert(arr1, 2, 8)

print(arr1) # Output: [1 2 8 3 4 5]

x = np.array([1, 2, 3])

# Insert x array at index 2
arr1 = np.insert(arr1, 2, x)

print(arr1) # Output: [1 2 1 2 3 8 3 4 5]


# 2D array (matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr2)

# Insert row at index 1 in a 2D array
new_row = np.array([20, 21, 22])

# Axis = 0 adds the items vertically
arr2 = np.insert(arr2, 1, new_row, axis=0)

print(arr2)

new_column = np.array([13, 14, 15, 16])

# Axis = 1 adds the items horizontally
arr2 = np.insert(arr2, 1, new_column, axis=1)

print(arr2)


[1 2 3 4 5]
[1 2 8 3 4 5]
[1 2 1 2 3 8 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [20 21 22]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 13  2  3]
 [20 14 21 22]
 [ 4 15  5  6]
 [ 7 16  8  9]]


**Deleting rows/columns**

In [172]:
# 1D array
arr1 = np.array([1, 2, 3, 4, 5])

print(arr1) # Output: [1 2 3 4 5]

# Delete element at index 2 from a 1D array
arr1 = np.delete(arr1, 2)

print(arr1) # Output: [1 2 4 5]

# Indexes to delete
indexes_to_delete = [1, 3]

# Delete elements at specified indexes
arr1 = np.delete(arr1, indexes_to_delete)

print(arr1) # Output: [1 4]



# 2D array (matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

print(arr2)

# Delete row at index 1 from a 2D array
arr2 = np.delete(arr2, 1, axis=0)

print(arr2)

# Rows to delete
rows_to_delete = [0, 2]

arr2 = np.delete(arr2, rows_to_delete, axis=0)

print(arr2)


arr3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

print(arr3)

# Delete column at index 0 and 2 from a 2D array
arr3 = np.delete(arr3, [0,2], axis=1)

print(arr3)



[1 2 3 4 5]
[1 2 4 5]
[1 4]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 7  8  9]
 [10 11 12]]
[[7 8 9]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 2]
 [ 5]
 [ 8]
 [11]]


**Removing specific elements**

In [235]:
# 1D array
arr1 = np.array([1, 2, 3, 4, 5])

print(arr1)

# Remove element with value 3 from a 1D array
arr1 = arr1[arr1 != 3]

print(arr1)

# Identify indices where the values are not 2 or 4
indices_to_keep = (arr1 != 2) & (arr1 != 4)

print(indices_to_keep)

# Remove element with value 2 and 4 from a 1D array
arr1 = arr1[indices_to_keep]

print(arr1)



[1 2 3 4 5]
[1 2 4 5]
[ True False False  True]
[1 5]


In [14]:
# 1D array
arr1 = np.array([1, 2, 3, 4, 5])

# 2D array (matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Addition
result_addition = arr1 + arr1
print(result_addition) #Output: [ 2 4 6 8 10]

# Multiplication
result_multiplication = arr2 * 3
print(result_multiplication)

#Output:
#[[ 3  6  9]
# [12 15 18]
# [21 24 27]]

# Element-wise square root
result_sqrt = np.sqrt(arr1)
print(result_sqrt) #Output: [1. 1.41421356 1.73205081 2. 2.23606798]

# Matrix multiplication (dot product)
result_matrix_mul = np.dot(arr2, arr2)
print(result_matrix_mul)

#Output:
#[[ 30  36  42]
# [ 66  81  96]
# [102 126 150]]

# Transpose of the matrix
transposed_matrix = arr2.T
print(transposed_matrix)

#Output:
#[[1 4 7]
# [2 5 8]
# [3 6 9]]

# Flatten array
flattened_array = arr2.flatten()  # Flatten to a 1D array
print(flattened_array) #Output: [1 2 3 4 5 6 7 8 9]

ravel = arr2.ravel()
print(ravel) #Output: [1 2 3 4 5 6 7 8 9]

# Vertically stack two arrays
stacked_vertically = np.vstack((arr1, arr1))
print(stacked_vertically)

#Output:
#[[1 2 3 4 5]
# [1 2 3 4 5]]

# Horizontally stack two arrays
stacked_horizontally = np.hstack((arr2, arr2))
print(stacked_horizontally)

#Output:
#[[1 2 3 1 2 3]
# [4 5 6 4 5 6]
# [7 8 9 7 8 9]]

# Concatenation
concatenated_array = np.concatenate((arr1, arr1))
print(concatenated_array) #Output: [1 2 3 4 5 1 2 3 4 5]

# Splitting
split_arrays = np.split(arr1, [2, 3, 4])  # Split into four arrays at indices 2, 3 and 4
print(split_arrays) #Output: [array([1, 2]), array([3]), array([4]), array([5])]

[ 2  4  6  8 10]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[1.         1.41421356 1.73205081 2.         2.23606798]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]
 [1 2 3 4 5]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
[1 2 3 4 5 1 2 3 4 5]
[array([1, 2]), array([3]), array([4]), array([5])]


Iterating over arrays:

In [247]:
# 1D array
arr1 = np.array([1, 2, 3, 4, 5])

# 2D array (matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Iterating over elements
for element in arr1:
    print(element)

# Iterating over rows (for 2D array)
for row in arr2:
    print(row)

# Iterating over elements using nditer
for element in np.nditer(arr2):
    print(element)

1
2
3
4
5
[1 2 3]
[4 5 6]
[7 8 9]
1
2
3
4
5
6
7
8
9


Basic mathematical functions:

In [255]:
# 1D array
arr1 = np.array([1, 2, 3, 4, 5])

# 2D array (matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(np.sum(arr2))
print(np.min(arr2))
print(np.max(arr2))
print(np.sqrt(arr2))

45
1
9
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]
